use_frameworks!

platform :ios, '8.0'

target 'AFNetworkingMetricsLog_Example' do
  pod 'AFNetworkingMetricsLog', :path => '../'

  target 'AFNetworkingMetricsLog_Tests' do
    inherit! :search_paths

    
  end
end
